spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/water_order
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
server:
  port: 8081
---
spring:
  profiles: production
server:
  port: 8082