spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
server:
  port: 8081
---
spring:
  profiles: production
server:
  port: 8082