spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
kerberos:
  ad-domain: rosseti.ural
  ad-server: ldap://s-dc01.rosseti.ural
  service-principal: HTTP/10.81.5.100:8081@rosseti.ural
  keytab-location: /keytab/waterorder.keytab
  ldap-search-base: dc=rosseti,dc=ural
  ldap-search-filter: "(| (userPrincipalName={0}) (sAMAccountName={0}))"
server:
  port: 8081
---
spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
server:
  port: 8082